server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${drinktea.datasource.driver-class-name}
      url: jdbc:mysql://${drinktea.datasource.host}:${drinktea.datasource.port}/${drinktea.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${drinktea.datasource.username}
      password: ${drinktea.datasource.password}
  redis:
    host: ${drinktea.redis.host}
    port: ${drinktea.redis.port}
    password: ${drinktea.redis.password}
    database: ${drinktea.redis.database}


mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.drinktea.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      drinktea:
        mapper: debug
        service: info
        controller: info

drinktea:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: itheima
    # 设置jwt过期时间
    user-ttl: 7200000
    # 设置前端传递过来的令牌名称
    user-token-name: authentication
  alioss:
    endpoint: ${drinktea.alioss.endpoint}
    access-key-id: ${drinktea.alioss.access-key-id}
    access-key-secret: ${drinktea.alioss.access-key-secret}
    bucket-name: ${drinktea.alioss.bucket-name}
  wechat:
    appid: ${drinktea.wechat.appid}
    secret: ${drinktea.wechat.secret}

